version: '3.8'

services:
  postgres:
    container_name: seatudy-db
    image: bitnami/postgresql:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=db
    volumes:
      - postgres-data:/bitnami/postgresql
    hostname: postgres-server
    networks:
      - seatudy-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - seatudy-network

networks:
  seatudy-network:

volumes:
  postgres-data:
